# fly.toml app configuration file generated for rag-fly-io on 2025-12-14T16:40:07Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rag-fly-io"
primary_region = "cdg"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = "off"
  min_machines_running = 1
  processes = ["app"]

[[http_service.checks]]
  grace_period = "180s"
  interval = "10s"
  timeout = "2s"
  method = "GET"
  path = "/"

[env]
  SPRING_APPLICATION_JSON = "{\"server\":{\"address\":\"0.0.0.0\",\"port\":8080}}"
  SPRING_PROFILES_ACTIVE = ""

[[vm]]
  memory = "2gb"
  cpu_kind = "shared"
  cpus = 1
