app = "rag-fly-io"
primary_region = "cdg"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = "off"
  min_machines_running = 1
  processes = ["app"]

[env]
  PORT = "8080"
  JAVA_TOOL_OPTIONS = "-Djava.net.preferIPv4Stack=true"
  SERVER_FORWARD_HEADERS_STRATEGY = "framework"


[[vm]]
  memory = "2gb"
  cpu_kind = "shared"
  cpus = 1
